development:
    adapter: mysql2
    database: kitchen_development
    username: root
    host: localhost

production:
    adapter: sqlite3
    database: db/kitchen_production.sqlite3
    pool: 5
    timeout: 5000
        
test:
    adapter: mysql2
    database: kitchen_test
    username: root
    host: localhost

pre:
    adapter: mysql2
    database: kitchen_development
    username: root
    host: localhost        
